// Dữ liệu tỉnh/thành phố Việt Nam
export const vietnamProvinces = [
  { code: "01", name: "Hà Nội" },
  { code: "02", name: "Hồ Chí Minh" },
  { code: "03", name: "Đà Nẵng" },
  { code: "04", name: "Hải Phòng" },
  { code: "05", name: "Cần Thơ" },
  { code: "06", name: "An Giang" },
  { code: "07", name: "Bà Rịa - Vũng Tàu" },
  { code: "08", name: "Bắc Giang" },
  { code: "09", name: "Bắc Kạn" },
  { code: "10", name: "Bạc Liêu" },
  { code: "11", name: "Bắc Ninh" },
  { code: "12", name: "Bến Tre" },
  { code: "13", name: "Bình Định" },
  { code: "14", name: "Bình Dương" },
  { code: "15", name: "Bình Phước" },
  { code: "16", name: "Bình Thuận" },
  { code: "17", name: "Cà Mau" },
  { code: "18", name: "Cao Bằng" },
  { code: "19", name: "Đắk Lắk" },
  { code: "20", name: "Đắk Nông" },
  { code: "21", name: "Điện Biên" },
  { code: "22", name: "Đồng Nai" },
  { code: "23", name: "Đồng Tháp" },
  { code: "24", name: "Gia Lai" },
  { code: "25", name: "Hà Giang" },
  { code: "26", name: "Hà Nam" },
  { code: "27", name: "Hà Tĩnh" },
  { code: "28", name: "Hải Dương" },
  { code: "29", name: "Hậu Giang" },
  { code: "30", name: "Hòa Bình" },
  { code: "31", name: "Hưng Yên" },
  { code: "32", name: "Khánh Hòa" },
  { code: "33", name: "Kiên Giang" },
  { code: "34", name: "Kon Tum" },
  { code: "35", name: "Lai Châu" },
  { code: "36", name: "Lâm Đồng" },
  { code: "37", name: "Lạng Sơn" },
  { code: "38", name: "Lào Cai" },
  { code: "39", name: "Long An" },
  { code: "40", name: "Nam Định" },
  { code: "41", name: "Nghệ An" },
  { code: "42", name: "Ninh Bình" },
  { code: "43", name: "Ninh Thuận" },
  { code: "44", name: "Phú Thọ" },
  { code: "45", name: "Phú Yên" },
  { code: "46", name: "Quảng Bình" },
  { code: "47", name: "Quảng Nam" },
  { code: "48", name: "Quảng Ngãi" },
  { code: "49", name: "Quảng Ninh" },
  { code: "50", name: "Quảng Trị" },
  { code: "51", name: "Sóc Trăng" },
  { code: "52", name: "Sơn La" },
  { code: "53", name: "Tây Ninh" },
  { code: "54", name: "Thái Bình" },
  { code: "55", name: "Thái Nguyên" },
  { code: "56", name: "Thanh Hóa" },
  { code: "57", name: "Thừa Thiên Huế" },
  { code: "58", name: "Tiền Giang" },
  { code: "59", name: "Trà Vinh" },
  { code: "60", name: "Tuyên Quang" },
  { code: "61", name: "Vĩnh Long" },
  { code: "62", name: "Vĩnh Phúc" },
  { code: "63", name: "Yên Bái" },
]

// Dữ liệu quận/huyện theo tỉnh/thành phố
const districtsByProvince: Record<string, { code: string; name: string }[]> = {
  "Hà Nội": [
    { code: "001", name: "Ba Đình" },
    { code: "002", name: "Hoàn Kiếm" },
    { code: "003", name: "Tây Hồ" },
    { code: "004", name: "Long Biên" },
    { code: "005", name: "Cầu Giấy" },
    { code: "006", name: "Đống Đa" },
    { code: "007", name: "Hai Bà Trưng" },
    { code: "008", name: "Hoàng Mai" },
    { code: "009", name: "Thanh Xuân" },
    { code: "010", name: "Hà Đông" },
    { code: "011", name: "Sơn Tây" },
    { code: "012", name: "Ba Vì" },
    { code: "013", name: "Chương Mỹ" },
    { code: "014", name: "Đan Phượng" },
    { code: "015", name: "Đông Anh" },
    { code: "016", name: "Gia Lâm" },
    { code: "017", name: "Hoài Đức" },
    { code: "018", name: "Mê Linh" },
    { code: "019", name: "Mỹ Đức" },
    { code: "020", name: "Phú Xuyên" },
    { code: "021", name: "Phúc Thọ" },
    { code: "022", name: "Quốc Oai" },
    { code: "023", name: "Sóc Sơn" },
    { code: "024", name: "Thạch Thất" },
    { code: "025", name: "Thanh Oai" },
    { code: "026", name: "Thanh Trì" },
    { code: "027", name: "Thường Tín" },
    { code: "028", name: "Ứng Hòa" },
    { code: "029", name: "Nam Từ Liêm" },
    { code: "030", name: "Bắc Từ Liêm" },
  ],
  "Hồ Chí Minh": [
    { code: "031", name: "Quận 1" },
    { code: "032", name: "Quận 3" },
    { code: "033", name: "Quận 4" },
    { code: "034", name: "Quận 5" },
    { code: "035", name: "Quận 6" },
    { code: "036", name: "Quận 7" },
    { code: "037", name: "Quận 8" },
    { code: "038", name: "Quận 10" },
    { code: "039", name: "Quận 11" },
    { code: "040", name: "Quận 12" },
    { code: "041", name: "Thủ Đức" },
    { code: "042", name: "Gò Vấp" },
    { code: "043", name: "Bình Thạnh" },
    { code: "044", name: "Tân Bình" },
    { code: "045", name: "Tân Phú" },
    { code: "046", name: "Phú Nhuận" },
    { code: "047", name: "Bình Tân" },
    { code: "048", name: "Củ Chi" },
    { code: "049", name: "Hóc Môn" },
    { code: "050", name: "Bình Chánh" },
    { code: "051", name: "Nhà Bè" },
    { code: "052", name: "Cần Giờ" },
  ],
  "Đà Nẵng": [
    { code: "053", name: "Liên Chiểu" },
    { code: "054", name: "Thanh Khê" },
    { code: "055", name: "Hải Châu" },
    { code: "056", name: "Sơn Trà" },
    { code: "057", name: "Ngũ Hành Sơn" },
    { code: "058", name: "Cẩm Lệ" },
    { code: "059", name: "Hòa Vang" },
  ],
}

// Dữ liệu phường/xã theo quận/huyện
const wardsByDistrict: Record<string, { code: string; name: string }[]> = {
  "Ba Đình": [
    { code: "00001", name: "Phúc Xá" },
    { code: "00002", name: "Trúc Bạch" },
    { code: "00003", name: "Vĩnh Phúc" },
    { code: "00004", name: "Cống Vị" },
    { code: "00005", name: "Liễu Giai" },
    { code: "00006", name: "Nguyễn Trung Trực" },
    { code: "00007", name: "Quán Thánh" },
    { code: "00008", name: "Ngọc Hà" },
    { code: "00009", name: "Điện Biên" },
    { code: "00010", name: "Đội Cấn" },
    { code: "00011", name: "Ngọc Khánh" },
    { code: "00012", name: "Kim Mã" },
    { code: "00013", name: "Giảng Võ" },
    { code: "00014", name: "Thành Công" },
  ],
  "Hoàn Kiếm": [
    { code: "00015", name: "Phúc Tân" },
    { code: "00016", name: "Đồng Xuân" },
    { code: "00017", name: "Hàng Mã" },
    { code: "00018", name: "Hàng Buồm" },
    { code: "00019", name: "Hàng Đào" },
    { code: "00020", name: "Hàng Bồ" },
    { code: "00021", name: "Cửa Đông" },
    { code: "00022", name: "Lý Thái Tổ" },
    { code: "00023", name: "Hàng Bạc" },
    { code: "00024", name: "Hàng Gai" },
    { code: "00025", name: "Chương Dương" },
    { code: "00026", name: "Hàng Trống" },
    { code: "00027", name: "Cửa Nam" },
    { code: "00028", name: "Hàng Bông" },
    { code: "00029", name: "Tràng Tiền" },
    { code: "00030", name: "Trần Hưng Đạo" },
    { code: "00031", name: "Phan Chu Trinh" },
    { code: "00032", name: "Hàng Bài" },
  ],
  "Quận 1": [
    { code: "00033", name: "Tân Định" },
    { code: "00034", name: "Đa Kao" },
    { code: "00035", name: "Bến Nghé" },
    { code: "00036", name: "Bến Thành" },
    { code: "00037", name: "Nguyễn Thái Bình" },
    { code: "00038", name: "Phạm Ngũ Lão" },
    { code: "00039", name: "Cầu Ông Lãnh" },
    { code: "00040", name: "Cô Giang" },
    { code: "00041", name: "Nguyễn Cư Trinh" },
    { code: "00042", name: "Cầu Kho" },
  ],
}

// Hàm lấy danh sách quận/huyện theo tỉnh/thành phố
export function getDistrictsByProvince(provinceName: string) {
  return districtsByProvince[provinceName] || []
}

// Hàm lấy danh sách phường/xã theo quận/huyện
export function getWardsByDistrict(districtName: string) {
  return wardsByDistrict[districtName] || []
}

